name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Build-Linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      # 安装Qt
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.2.4'
          host: 'linux'
          arch: 'gcc_64'
          target: 'desktop'
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      # 拉取子仓库
      - name: Checkout submodules
        run: git submodule update --init --recursive
      # 编译构建
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make
      # 上传artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: colutius-desktop
          path: /home/runner/work/colutius-desktop/colutius-desktop/build
          if-no-files-found: error
